apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
spec:
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
        version: "200"
    spec:
      containers:
      - name: simulator
        image: gabsferrara/circuit-breaker-example-go:latest
        ports:
        - containerPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-error
spec:
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
        version: "504"
    spec:
      containers:
      - name: simulator
        image: gabsferrara/circuit-breaker-example-go:latest
        ports:
        - containerPort: 8000
        env:
          - name: error
            value: "yes"

---

apiVersion: v1
kind: Service
metadata:
  name: simulator-service
spec:
  type: ClusterIP
  selector:
    app: simulator 
  ports:
  - port: 80
    targetPort: 8000